---
title: "DS421 Replication"
author: "Yiyi, Arfa and Elif"
date: "9/25/2019"
output: html_document

---
### Load libraries

```{r warning=FALSE}
library(dplyr)
library(readstata13)
library(ggplot2)
library(tidyr)
```

### Load data

```{r}
# loads data from 
baseline <- read.dta13("data/baselineData.dta")
country <- read.dta13("data/countryData.dta")
nex <- read.dta13("data/NEXdata.dta")
climate <- read.dta13("data/uniformClimateChange.dta")
additional <- read.dta13("data/additionalData.dta")
```


```{r}
summary <- baseline %>%
  select(originCountryName, year, applications, tAvgDEL) %>%
  mutate(log_app = log(applications)) %>%
  group_by(originCountryName) %>%
  summarise(min_log_app = min(log_app, na.rm = TRUE),
            mean_log_app = mean(log_app, na.rm = TRUE),
            max_log_app = max(log_app, na.rm = TRUE),
            min_temp = min(tAvgDEL, na.rm = TRUE),
            mean_temp = mean(tAvgDEL, na.rm = TRUE),
            max_temp = max(tAvgDEL, na.rm = TRUE)) %>%
  filter(mean_log_app > 0)
```

scatter plot with range of log assylum applications for each country
```{r}
ggplot(summary, aes(x = mean_temp, y = mean_log_app)) + 
  geom_point() + 
  geom_errorbar(mapping = aes(x = mean_temp, ymin = min_log_app, ymax = max_log_app)) +
  geom_text(aes(label=originCountryName),hjust=0, vjust=0)
```
  
scatter plot with range of temperatures for each country
```{r}
ggplot(summary, aes(x = mean_log_app, y = mean_temp)) + 
  geom_point() + 
  geom_errorbar(mapping = aes(x = mean_log_app, ymin = min_temp, ymax = max_temp)) +
  geom_text(aes(label=originCountryName),hjust=0, vjust=0) +
  coord_flip()
```



